window.APP_CONFIG = {
  "app": {
    "title": "台灣業餘無線電資格測試學習法",
    "subtitle": "ANKI 權重學習法"
  },
  "home": {
    "configFileLabel": "⚙️ 設定檔 (選擇性，.json)",
    "configFileHint": "例：config.json　（省略則使用預設文字）",
    "questionFileLabel": "📂 *題庫檔案 (必要，.csv)",
    "questionFileHint": "例：無線電通訊方法題庫.csv",
    "weightFileLabel": "📊 權重檔案 (選擇性，.csv)",
    "weightFileHint": "例：weight_無線電通訊方法題庫.csv　（省略則以全新等權重開始）",
    "explainFileLabel": "💡 解題說明檔 (選擇性，.md)",
    "explainFileHint": "例：Ans_射頻干擾預防與排除技術問題解析18題.md　（省略則答題後不顯示解說）",
    "roundSizeLabel": "📝 每回合題數",
    "round35Label": "35 題（通過需 25 題）",
    "round40Label": "40 題（通過需 32 題）",
    "round50Label": "50 題（通過需 40 題）",
    "loadButton": "載入檔案"
  },
  "info": {
    "pageTitle": "測驗資訊確認",
    "poolNumLabel": "題庫總題數",
    "unitQuestion": "題",
    "weightStatusLabel": "權重狀態",
    "explainStatusLabel": "解說檔狀態",
    "learnedLabel": "已熟練（Easy，下回不出）",
    "unlearnedLabel": "待學習（尚未標 Easy）",
    "testNumLabel": "本回合出題數",
    "passLineLabel": "通過標準",
    "startButton": "開始測驗",
    "resetStartButton": "重置並開始（已全部熟練）",
    "backButton": "重新上傳檔案"
  },
  "quiz": {
    "counterTemplate": "第 {pos} / {total} 題",
    "correctTemplate": "答對：{count}",
    "questionPrefix": "第 {pos} 題",
    "explainTitle": "💡 相關技術解說",
    "ankiLabel": "請標記此題難易度：",
    "hell": { "label": "HELL", "desc": "非常困難" },
    "hard": { "label": "HARD", "desc": "困難" },
    "good": { "label": "GOOD", "desc": "普通" },
    "easy": { "label": "EASY", "desc": "已熟練" }
  },
  "result": {
    "pageTitle": "測驗結果",
    "pctTemplate": "正確率：{pct}%",
    "passText": "及格 PASS ✓",
    "failText": "不及格 FAIL ✗",
    "saveButton": "儲存進度並繼續",
    "saveButtonSub": "（儲存權重 → 資訊頁）",
    "resetButton": "清空進度重練",
    "resetButtonSub": "（重置所有權重 → 資訊頁）"
  },
  "messages": {
    "noQuestionFile": "請選取題庫檔案！",
    "configParseError": "設定檔解析失敗，將使用預設設定。\n",
    "parseError": "題庫解析失敗，請確認 CSV 格式。",
    "readError": "檔案讀取或解析失敗，請檢查檔案內容。\n",
    "noQuestions": "無法生成題目，請確認題庫。",
    "weightNew": "全新開始（等權重）",
    "weightLoaded": "已載入歷史權重",
    "weightMismatch": "⚠️ 權重檔題數（{wCount} 題）與題庫題數（{qCount} 題）不符，已忽略權重檔，改以等權重開始。",
    "weightMismatchStatus": "權重檔不符（已忽略）",
    "explainNotLoaded": "未載入",
    "explainParseError": "⚠️ 解說檔無法解析（格式不符或題號未匹配），已忽略解說檔。",
    "explainParseErrorStatus": "解說檔格式錯誤（已忽略）",
    "explainPartial": "已載入部分解說（{matched} / {total} 題）",
    "explainFull": "已載入完整解說（{matched} 題）",
    "allEasyInfo": "所有題目均已標記為 Easy（熟練）！按下按鈕後系統將重置所有權重並立即開始新回合。",
    "allEasyPassLine": "—（所有題目已熟練，按下按鈕後重置並立即開始新回合）",
    "passLinePartial": "{needed} 題（{actual} 題 × 80%，因可出題數不足一回合）",
    "passLineFull": "{needed} 題正確（{roundSize} 題制標準）",
    "confirmReset": "確定要清空所有學習進度，將所有題目重置為等權重嗎？",
    "resetDone": "⚠️ 您選擇了【清空進度重練】，所有題目已重置為等權重。",
    "resetStatus": "重置為等權重",
    "saveDone": "✅ 您選擇了【儲存並繼續】，學習進度已儲存，請開始下一回合。",
    "answerCorrect": "✅ <strong>答對了！</strong>　正確答案為選項 ({ans})",
    "answerWrong": "❌ <strong>答錯了！</strong>　正確答案為選項 ({ans})",
    "resultNotePartial": "本回合實際出題 {actual} 題（可出題數不足 {roundSize} 題），以 80% 為通過標準，需答對 {needed} 題。",
    "resultNoteFull": "本回合 {roundSize} 題制，通過標準為答對 {needed} 題。"
  }
};
